# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (7)
# #########################################################################

class ClassificationResult(BaseModel):
    model_reasoning: typing.Optional[str] = Field(default=None, description='Step-by-step reasoning explaining why this theme was chosen')
    chosen_theme_title: typing.Optional[str] = Field(default=None, description='The title of the theme that best matches the input text. Must match exactly one of the provided theme titles.')

class ComplementaryInfo(BaseModel):
    model_config = ConfigDict(extra='allow')

class ContactInfo(BaseModel):
    model_config = ConfigDict(extra='allow')
    email: typing.Optional[str] = Field(default=None, description='Customer\'s email address, null if not provided')
    phone: typing.Optional[str] = Field(default=None, description='Customer\'s phone number, null if not provided or refused')
    preferred_contact_method: typing.Optional[typing.Union[types.ContactMethod, str]] = Field(default=None, description='Preferred contact method, null if not mentioned')
    call_reasons: typing.Optional[typing.List[str]] = Field(default=None, description='Reasons for the call, null if not specified')

class CustomerForm(BaseModel):
    personal_info: typing.Optional["PersonalInfo"] = None
    contact_info: typing.Optional["ContactInfo"] = None

class DynamicOutput(BaseModel):
    personal_info: typing.Optional["PersonalInfo"] = None
    contact_info: typing.Optional["ContactInfo"] = None
    complementary_info: typing.Optional["ComplementaryInfo"] = None

class PersonalInfo(BaseModel):
    model_config = ConfigDict(extra='allow')
    first_name: typing.Optional[str] = Field(default=None, description='Customer\'s first name')
    last_name: typing.Optional[str] = Field(default=None, description='Customer\'s last name')
    gender: typing.Optional[types.Gender] = Field(default=None, description='Customer\'s gender: use Refused if the customer explicitly declines to answer, Other if unknown or unspecified')

class Theme(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
