# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClassificationResult": types.ClassificationResult,
    "stream_types.ClassificationResult": stream_types.ClassificationResult,

    "types.ComplementaryInfo": types.ComplementaryInfo,
    "stream_types.ComplementaryInfo": stream_types.ComplementaryInfo,

    "types.ContactInfo": types.ContactInfo,
    "stream_types.ContactInfo": stream_types.ContactInfo,

    "types.CustomerForm": types.CustomerForm,
    "stream_types.CustomerForm": stream_types.CustomerForm,

    "types.DynamicOutput": types.DynamicOutput,
    "stream_types.DynamicOutput": stream_types.DynamicOutput,

    "types.PersonalInfo": types.PersonalInfo,
    "stream_types.PersonalInfo": stream_types.PersonalInfo,

    "types.Theme": types.Theme,
    "stream_types.Theme": stream_types.Theme,


    "types.ContactMethod": types.ContactMethod,

    "types.Gender": types.Gender,

}