# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class ContactMethod(str, Enum):
    Email = "Email"
    Phone = "Phone"

class Gender(str, Enum):
    Male = "Male"
    Female = "Female"
    Other = "Other"
    Refused = "Refused"

# #########################################################################
# Generated classes (7)
# #########################################################################

class ClassificationResult(BaseModel):
    model_reasoning: str = Field(description='Step-by-step reasoning explaining why this theme was chosen')
    chosen_theme_title: str = Field(description='The title of the theme that best matches the input text. Must match exactly one of the provided theme titles.')

class ComplementaryInfo(BaseModel):
    model_config = ConfigDict(extra='allow')

class ContactInfo(BaseModel):
    model_config = ConfigDict(extra='allow')
    email: typing.Optional[str] = Field(default=None, description='Customer\'s email address, null if not provided')
    phone: typing.Optional[str] = Field(default=None, description='Customer\'s phone number, null if not provided or refused')
    preferred_contact_method: typing.Optional[typing.Union[ContactMethod, str]] = Field(default=None, description='Preferred contact method, null if not mentioned')
    call_reasons: typing.Optional[typing.List[str]] = Field(default=None, description='Reasons for the call, null if not specified')

class CustomerForm(BaseModel):
    personal_info: "PersonalInfo"
    contact_info: "ContactInfo"

class DynamicOutput(BaseModel):
    personal_info: "PersonalInfo"
    contact_info: "ContactInfo"
    complementary_info: typing.Optional["ComplementaryInfo"] = None

class PersonalInfo(BaseModel):
    model_config = ConfigDict(extra='allow')
    first_name: str = Field(description='Customer\'s first name')
    last_name: str = Field(description='Customer\'s last name')
    gender: Gender = Field(description='Customer\'s gender: use Refused if the customer explicitly declines to answer, Other if unknown or unspecified')

class Theme(BaseModel):
    title: str
    description: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
